// Seed data for schools, classes, teachers, students, and attendance
const seed_data = [
  // Schools
  { table_name: "schools", school_id: 1, school_name: 'Boulder High School', city: 'Boulder', state: 'CO'},

  // Classes
  { table_name: "classes", class_name: 'Math 101', school_id: 1},
  { table_name: "classes", class_name: 'English 101', school_id: 1},
  { table_name: "classes", class_name: 'Science 101', school_id: 1},
  { table_name: "classes", class_name: 'Home Economics 101', school_id: 1},
  { table_name: "classes", class_name: 'Recreation 101', school_id: 1},

  // Teachers
  { table_name: "teachers", first_name: 'Steve', last_name: 'Calla', email_address: 'callasteven@gmail.com', class_id: 1},
  { table_name: "teachers", first_name: 'Patrick', last_name: 'Black', email_address: 'pat@safermgmt.com', class_id: 2},
  { table_name: "teachers", first_name: 'Bessie', last_name: 'Doodle', email_address: '', class_id: 3},
  { table_name: "teachers", first_name: 'Tom', last_name: 'Horsh', email_address: '', class_id: 4},
  { table_name: "teachers", first_name: 'Robert', last_name: 'Griffin', email_address: '', class_id: 5},

  // Students
  {table_name: "students", first_name: "Annabela", last_name: "Jeays", school_id: "1", class_id: "1"},   
  {table_name: "students", first_name: "Simonette", last_name: "Screach", school_id: "1", class_id: "1"}, 
  {table_name: "students", first_name: "Billie", last_name: "Barby", school_id: "1", class_id: "1"}, 
  {table_name: "students", first_name: "Mona", last_name: "Pierton", school_id: "1", class_id: "2"}, 
  {table_name: "students", first_name: "Rawley", last_name: "Orteaux", school_id: "1", class_id: "2"}, 
  {table_name: "students", first_name: "Sylas", last_name: "Castellini", school_id: "1", class_id: "2"},

  // Attendance
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 1, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 2, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 3, attendance_date: '2024-04-15', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 1, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 2, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 3, attendance_date: '2024-04-16', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 1, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 2, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 3, attendance_date: '2024-04-17', is_present: false, notes: ""},

  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 4, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 5, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 6, attendance_date: '2024-04-15', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 4, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 5, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 6, attendance_date: '2024-04-16', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 4, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 5, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 6, attendance_date: '2024-04-17', is_present: false, notes: ""},
  
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 1, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 2, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 3, attendance_date: '2024-04-15', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 1, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 2, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 3, attendance_date: '2024-04-16', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 1, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 2, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 3, attendance_date: '2024-04-17', is_present: false, notes: ""},
  
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 1, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 2, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 3, attendance_date: '2024-04-15', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 1, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 2, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 3, attendance_date: '2024-04-16', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 1, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 2, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 3, attendance_date: '2024-04-17', is_present: false, notes: ""},

  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 4, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 5, attendance_date: '2024-04-15', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 6, attendance_date: '2024-04-15', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 4, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 5, attendance_date: '2024-04-16', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 6, attendance_date: '2024-04-16', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 4, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 5, attendance_date: '2024-04-17', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 6, attendance_date: '2024-04-17', is_present: false, notes: ""},

  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 1, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 2, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 3, attendance_date: '2024-04-18', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 1, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 2, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 3, attendance_date: '2024-04-19', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 1, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 2, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 3, attendance_date: '2024-04-22', is_present: false, notes: ""},

  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 4, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 5, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 6, attendance_date: '2024-04-18', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 4, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 5, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 6, attendance_date: '2024-04-19', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 4, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 5, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 6, attendance_date: '2024-04-22', is_present: false, notes: ""},
  
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 1, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 2, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 3, attendance_date: '2024-04-18', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 1, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 2, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 3, attendance_date: '2024-04-19', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 1, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 2, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 3, attendance_date: '2024-04-22', is_present: false, notes: ""},
  
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 1, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 2, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 3, attendance_date: '2024-04-18', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 1, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 2, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 3, attendance_date: '2024-04-19', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 1, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 2, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 3, attendance_date: '2024-04-22', is_present: false, notes: ""},

  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 4, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 5, attendance_date: '2024-04-18', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 6, attendance_date: '2024-04-18', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 4, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 5, attendance_date: '2024-04-19', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 6, attendance_date: '2024-04-19', is_present: false, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 4, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 5, attendance_date: '2024-04-22', is_present: true, notes: ""},
  { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 6, attendance_date: '2024-04-22', is_present: false, notes: ""},

    { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 1, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 2, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 3, attendance_date: '2024-04-23', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 1, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 2, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 3, attendance_date: '2024-04-24', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 1, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 2, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 1, teacher_id: 1, student_id: 3, attendance_date: '2024-04-25', is_present: false, notes: ""},
  
    { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 4, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 5, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 6, attendance_date: '2024-04-23', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 4, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 5, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 6, attendance_date: '2024-04-24', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 4, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 5, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 2, teacher_id: 2, student_id: 6, attendance_date: '2024-04-25', is_present: false, notes: ""},
    
    { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 1, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 2, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 3, attendance_date: '2024-04-23', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 1, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 2, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 3, attendance_date: '2024-04-24', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 1, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 2, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 3, teacher_id: 3, student_id: 3, attendance_date: '2024-04-25', is_present: false, notes: ""},
    
    { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 1, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 2, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 3, attendance_date: '2024-04-23', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 1, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 2, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 3, attendance_date: '2024-04-24', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 1, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 2, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 4, teacher_id: 4, student_id: 3, attendance_date: '2024-04-25', is_present: false, notes: ""},
  
    { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 4, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 5, attendance_date: '2024-04-23', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 6, attendance_date: '2024-04-23', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 4, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 5, attendance_date: '2024-04-24', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 6, attendance_date: '2024-04-24', is_present: false, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 4, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 5, attendance_date: '2024-04-25', is_present: true, notes: ""},
    { table_name: "attendance", school_id: 1, class_id: 5, teacher_id: 5, student_id: 6, attendance_date: '2024-04-25', is_present: false, notes: ""},
];

module.exports = {
  seed_data
}